"""empty message

Revision ID: cf80d303e86f
Revises: f240ff7795a9
Create Date: 2023-08-22 21:23:06.012752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf80d303e86f'
down_revision: Union[str, None] = 'f240ff7795a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('rages_buyback', sa.Boolean(), nullable=False, server_default="0"))
    op.add_column('players', sa.Column('bm_pause', sa.Boolean(), nullable=False, server_default="0"))
    op.add_column('players', sa.Column('resumes_pause', sa.Boolean(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'resumes_pause')
    op.drop_column('players', 'bm_pause')
    op.drop_column('players', 'rages_buyback')
    # ### end Alembic commands ###
