"""empty message

Revision ID: f240ff7795a9
Revises: 
Create Date: 2023-08-21 19:37:01.225744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f240ff7795a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('steam_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pro_name', sa.String(), nullable=True),
    sa.Column('custom_name', sa.String(), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.Column('smurf', sa.String(), nullable=False),
    sa.Column('smurf_stratz', sa.Integer(), nullable=True),
    sa.Column('is_racist', sa.Boolean(), nullable=False),
    sa.Column('is_sexist', sa.Boolean(), nullable=False),
    sa.Column('is_toxic', sa.Boolean(), nullable=False),
    sa.Column('is_feeder', sa.Boolean(), nullable=False),
    sa.Column('gives_up', sa.Boolean(), nullable=False),
    sa.Column('destroys_items', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('steam_id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('players')
    # ### end Alembic commands ###
